### ISSUE TITLE
Music!

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/stnicc-beeb#11]
Integrate most recent / optimised music player (is this from Wave Runner or use Simon's LZ compressor?)

Pick awesome music, ideally an SN version of ChechnoBankh if we can..

**Comment by simondotm** [comment]
Assign this one to me if you like. I'll progress the checknobank tune to see what we can get

**Comment by kieranhj** [comment]
Rhino is on the case for composing the music. :)
Will need some work to integrate the music player with the interrupt driven render routine. Probably our biggest remaining risk.
Intro & outro can have separate tunes and players as appropriate.

**Comment by kieranhj** [comment]
Music has been added, waiting final assets.
