### ISSUE TITLE
NULA version?

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/stnicc-beeb#16]
It would be possible to make a custom NULA version that runs in MODE 8 but with full 16 colour palette. Not sure what to do about the resolution though as 64x100 is going to look super-chunky.

There might be some optimisations to be made since we wouldn't require the dithering pattern for the palette?

**Comment by kieranhj** [comment]
Has to be 32 columns as relies on 256 byte stride for screen rows. Would make the pixel masking simpler though and could be made immediate values.

**Comment by simondotm** [comment]
UPVOTE!

**Comment by kieranhj** [comment]
This works. Or at least used to. Haven't tried it in a while. :)
