### ISSUE TITLE
Stream runs out of data in low quality mode

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/stnicc-beeb#22]
Can’t quite complete the sequence - crash on frame &653 when swapping to final disc. Our stream read ptr catches the load to ptr. It’s running too fast!!

**Comment by kieranhj** [comment]
I added a quick check only for when the frame aligns back to the start of the stream buffer to see if we're still loading that memory and block if so. It fixes the low quality buffer problem but still get glitches in wireframe mode as it's consuming data too fast not just when the frame aligns.

**Comment by kieranhj** [comment]
This blocks on a real floppy at low quality when switching to the last disc. It's not terrible and it doesn't crash. Might improve if/when we shift where the drive switches take place.

**Comment by tom-seddon** [comment]
Still bust in medium quality for me in b2 (haven't tested on my Master). High and low quality run to completion.
![image](https://user-images.githubusercontent.com/1269020/69287949-e842c280-0bef-11ea-93c1-2a5d08858480.png)
