### ISSUE TITLE
Unbreak NULA version for post-party release

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/stnicc-beeb#44]
I done broken the NULA version for the party version. Sorry.

**Comment by kieranhj** [comment]
Seems to work now the ROMSEL bug is fixed, although colours are a little weird.
Might be the way the palette entries are combined when dropping alternate frames in the encoder.py script.

**Comment by kieranhj** [comment]
Needs a NULA reset at the end of the sequence as well.

**Comment by tom-seddon** [comment]
Colours fixed by 96e586d318cc1023ad36e051fb5c5954de123a10 - palette entries weren't being written out in index order.

ae3e4a91259f0bfc459988d2931c6b598f6ac529 fixes the NuLA reset.

**Comment by tom-seddon** [comment]
I don't have a real NuLA to test this on btw. I've just tested this in b2.

**Comment by kieranhj** [comment]
I will test this on my NULA B before release.

**Comment by kieranhj** [comment]
Thanks for the fixes, I should add.

**Comment by kieranhj** [comment]
Works on real hw.
