### ISSUE TITLE
Open questions regarding NuLA quality level and overall timing

### ISSUE THREAD

**Issue by tom-seddon** [kieranhj/stnicc-beeb#52]
The batch files a quality=1 NuLA build, which looks pretty nice. The makefile build creates a quality=0 NuLA build, because then the demo finishes before the music, rather than the other way around.

4b481dc1f24d9079a65d2fa75b7e696a6b668282 adds a delay to the NuLA version so the quality=0 version runs in the same time as the non-NuLA version, so it finishes in time with the music. (Haven't tried this on real hardware, though... just b2.)

The quality=0 build does look a bit dim, of course, which might be objectionable. So perhaps we want quality=1 after all, get rid of the delay, avoid the temptation to re-open #25, and just live with the music finishing early?

**Comment by kieranhj** [comment]
Tom made everything awesome. Quality = 1 at same speed as the original. :)
