### ISSUE TITLE
Loader to select version.

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/stnicc-beeb#9]
Select low / medium / high quality
Select loop? (For ABUG type events)
Confirm SWRAM usage for music?
Select music on/off?
Must also work without input for online emulator.

**Comment by kieranhj** [comment]
Lower priority. Focus on auto-boot party version first:
Low quality only (for speed).
Music on.
Intro & outro, no looping.

NULA release can come later. @tom-seddon now has NULA auto-detection code.

**Comment by kieranhj** [comment]
Fine to be in BASIC if that's easier.
Autodetect swram, default to music on if available.
Autodetect NULA, default to NULA if available.
Allow user to change these options.
Timeout if no input in 10 seconds and run demo.

**Comment by kieranhj** [comment]
Loader now exists in nula-fix branch. Detects SWRAM using Tricky's code.
Boots directly to Intro, no interaction at the moment.

**Comment by tom-seddon** [comment]
Now detects NuLA and gives you the option of pressing space within 5 seconds to run the non-NuLA version.

**Comment by tom-seddon** [comment]
https://github.com/kieranhj/stnicc-beeb/commit/0528db0d4b8f1809a09fb4bf2be76ecb40ed7191 adds a toggle during the intro - press N.

**Comment by kieranhj** [comment]
It's not a glamorous loader but it works with zero intervention as everything is auto-detected. :)
